### ISSUE TITLE
Notifier Passwords error

### ISSUE THREAD

**Issue by SimplyCorbett** [nextcloud/passman#631] opened 2019-10-28 04:47 UTC
My error log is being spammed with the following on Nextcloud 17.0.0:

`InvalidArgumentException: Notifier Passwords (id: passman) is not considered because it's using the old way to register`

How would one go about fixing this?

**Comment by darkernoise** [comment] 2019-11-04 17:20
It looks like this is related to https://github.com/nextcloud/passman/issues/610 and I see a patch committed.  Is there a need for testers to help move this to mater?

**Comment by GuidoDr** [comment] 2019-11-05 10:50
I do see the same errors in our instance (17.0.0):

[no app in context] Error: InvalidArgumentException: Notifier Passwörter (id: passman) is not considered because it is using the old way to register. at <<closure>>

0. /var/www/html/custom_apps/passman/appinfo/app.php line 38
   OC\Notification\Manager->registerNotifier(Closure {}, Closure {})
1. /var/www/html/lib/private/legacy/app.php line 260
   undefinedundefinedrequire_once("/var/www/html/c ... p")
2. /var/www/html/lib/private/legacy/app.php line 154
   OC_App::requireAppFile(OCA\Passman\AppInfo\Application {})
3. /var/www/html/lib/private/legacy/app.php line 127
   OC_App::loadApp("passman")
4. /var/www/html/lib/base.php line 985
   OC_App::loadApps()
5. /var/www/html/index.php line 42
   OC::handleRequest()

**Comment by GuidoDr** [comment] 2019-11-12 07:21
same with the current NC version 17.0.1.1

[no app in context] Error: InvalidArgumentException: Notifier Passwörter (id: passman) is not considered because it is using the old way to register. at <<closure>>

0. /var/www/html/custom_apps/passman/appinfo/app.php line 38
   OC\Notification\Manager->registerNotifier(Closure {}, Closure {})
1. /var/www/html/lib/private/legacy/app.php line 260
   undefinedundefinedrequire_once("/var/www/html/c ... p")
2. /var/www/html/lib/private/legacy/app.php line 154
   OC_App::requireAppFile(OCA\Passman\AppInfo\Application {})
3. /var/www/html/lib/private/legacy/app.php line 127
   OC_App::loadApp("passman")
4. /var/www/html/lib/base.php line 985
   OC_App::loadApps()
5. /var/www/html/index.php line 42
   OC::handleRequest()

**Comment by darkernoise** [comment] 2019-11-18 14:36
@GuidoDR See https://github.com/nextcloud/passman/issues/628.  This issue is caused by changes in NC 17, which are not yet supported in Passman 2.3.4, but "should" be supported in the next version, 2.3.5.  In the meantime, there is a workaround in that you can disable the notifications code.  Details are in issue 628.

**Comment by GuidoDr** [comment] 2019-11-18 15:17
2.3.5 is available since a couple of hours and the problem is fixed in our NC 17 instance

**Closed** 2023-01-03 22:22 UTC
