### ISSUE TITLE
Add option to export & import passwords

### ISSUE THREAD

**Issue by RipperSK** [nextcloud/passman#805] opened 2023-09-03 20:13 UTC
## Feature request

**User type**: Logged-in user

**User level**: intermediate

### Description

I would like for Passman to have an option to export / import passwords into some common format (like CSV or XML) so that I do not have to worry that if my nextCloud instance gets hacked / deleted / server caches on fire - that my passwords that I no longer remeber due to Passman are somewhere safe.

### Benefit / value

Benefit for users is that they can import / export their passwords and migrate easily to / from another password manager or just that they can feel safe that even if passman stops working for some reason there's another way to access their passwords.

### Risk / caveats

Import feature would need to sanitize user inputs and input file so passwords do not get over-written / destroyed / passman kernel panics etc.
Caveat is that this enables users dissatisfied with passman to leave easily.
Good thing this enables users dissatisfied with passman alternative to migrate to passman easily.

### Sponsorship

 Not Available...

**Are you a developer willing to implement this feature?**: no

**Can you sponsor the development of this feature or do you know someone who can?**: no

**Comment by binsky08** [comment] 2023-09-04 05:55
We already support import / export for a vault. Just login to it and open vault setting and go to the export tab.

I'm not sure If exporting single credentials would be really useful.

**Comment by binsky08** [comment] 2024-04-05 21:16
Since password import/export is already implemented on vault level, this request sounds like a duplicate of an already existing functionality.

**Closed by binsky08** 2024-04-05 21:16 UTC
Labels: Feature request

**Comment by binsky08** [comment] 2025-08-13 22:17
technically possible, are ya willing to provide a pull request? I'd enjoy reviewing it :)
