### ISSUE TITLE
Upgrade from NC 26.0.1 to 27 beta1 - Autoload path not allowed

### ISSUE THREAD

**Issue by OsiMood** [nextcloud/passman#774] opened 2023-05-10 05:43 UTC
After running the upgrade script, I am running into this issue:

Failed to load repair step for passman: Autoload path not allowed: /var/www/html/nextcloud/apps/passman/migration/serversideencryption.php

Not sure what to do, try to remove the extension and put it back, still, same issue
Thank you

**Comment by binsky08** [comment] 2023-05-10 07:14
nc27 is not yet supported by Passman.
It might be a few weeks before I deal with it though.

**Comment by OsiMood** [comment] 2023-05-10 07:32
I unfortunately did the move and now can not access passwords.... my mistake but extremely painful lesson

**Comment by binsky08** [comment] 2023-05-10 08:13
The problem is that nc27 enforces [PSR-4 autoloading](https://www.php-fig.org/psr/psr-4/) / naming convention.

**Comment by OsiMood** [comment] 2023-05-10 08:17
is there any easy fix ? is there anything I can help with ?

**Comment by WN1188** [comment] 2023-06-14 20:26
Any updates on when 27.0.0 support will be added? Need any help on this one?

**Comment by binsky08** [comment] 2023-06-14 21:20
Hey @WN1188, currently trying to migrate Passman to nc27, but i have a blocking problem.

I already migrated that autoloading stuff.
After that, the frontend is kind of empty. (also in nc26 - so that's not a problem with nc27)
![image](https://github.com/nextcloud/passman/assets/30630233/a768ddc2-c097-4c77-b302-48f87c30664f)

Thats the only error I get:
![image](https://github.com/nextcloud/passman/assets/30630233/e63a61d5-9634-4ed2-b4fb-c1b7a6fcc436)

It has to be something with css or js, but that shouldn't have anything to do with the PHP controller logic.

The current state (checkout with nc26 (for dev reasons) should work as well): https://github.com/nextcloud/passman/tree/nc27

**Comment by binsky08** [comment] 2023-06-15 12:48
I was able to identify it as a problem with the ShareMiddleware and APIMiddleware.
But if I don't find a solution quickly, I won't be able to try again until next week.

**Comment by olodar** [comment] 2023-06-18 07:43
Same problem here.
Repair error: Autoload path not allowed: /var/www/html/apps/passman/migration/serversideencryption.php

sudo -u www-data php occ maintenance:repair 
Failed to load repair step for passman: Autoload path not allowed: /var/www/html/apps/passman/migration/serversideencryption.php

**Comment by binsky08** [comment] 2023-06-18 08:21
@olodar are you using the current app release from the nextcloud app store or the nc27 branch of this repo?

**Comment by olodar** [comment] 2023-06-18 09:24
> @olodar are you using the current app release from the nextcloud app store or the nc27 branch of this repo?

From NX app store. Before upgrade to NX 27 I have upgraded passman to 2.4.5.

**Comment by OsiMood** [comment] 2023-06-18 11:13
Just moved to the NC27 branch and while trying to repair, I get:
Failed to load repair step for passman: Autoload path not allowed: /var/www/html/nextcloud/apps/passman/migration/serversideencryption.php

Weird enough Passman is launching and working

**Comment by binsky08** [comment] 2023-06-19 22:34
thanks for the feedback
migration namespace in nc27 branch should be fixed

there will be a release as soon as one of the maintainers @animalillo @brantje  has time for a review and merge

**Comment by lcuis** [comment] 2023-06-24 22:09
Hi @binsky08 ,

Thanks a lot for looking into this issue.

I wanted to try your solution on my NC27 installation but this gives me new errors. Here is what I did:

1. ~~I downloaded your branch code from https://github.com/nextcloud/passman/archive/refs/heads/nc27.zip~~
2. ~~I unzipped~~
3. ~~rm -rf .d* .gitignore .jshintrc .scrutinizer.yml .travis.yml .tx/~~
4. ~~Replaced my installation of passman with this folder in nextcloud/apps~~
5. ~~Load /apps/passman/~~

I got the internal server error and the following log in the NextCloud admin logs page:
```
[index] Error: OC\AppFramework\Utility\QueryNotFoundException: Could not resolve OCA\Passman\Controller\PageController! Class "OCA\Passman\Controller\PageController" does not exist at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 142
   OC\AppFramework\Utility\SimpleContainer->resolve()
1. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 494
   OC\AppFramework\Utility\SimpleContainer->query()
2. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 466
   OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
3. /var/www/nextcloud/lib/private/AppFramework/App.php line 162
   OC\AppFramework\DependencyInjection\DIContainer->query()
4. /var/www/nextcloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
5. /var/www/nextcloud/lib/base.php line 1064
   OC\Route\Router->match()
6. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

GET /apps/passman/
```

There must be a process to prepare a release but I couldn't find it.

**Comment by binsky08** [comment] 2023-06-24 22:51
@lcuis um, that's kinda bad. Usually it should work with that kind of snapshot version from the repo.
Please try again with the current nc27 version (added a commit some hours ago).
Make sure there are correct file+folder permissions (or set `chmod -R 777 apps/passman`, but for testing only!)

Could you provide some specs about your installation (system, database, php version, nextcloud version)

**Comment by lcuis** [comment] 2023-06-24 23:08
Thanks a lot @binsky08 , my issue was simply with the permissions. I forgot this step:
```
chown www-data:www-data passman
```
I don't have any problematic logs anymore regarding passman.

I can now access my passwords from the NC27 web interface and from the app. Your NC27 branch worked like a charm for me.

Just for completion, here are the details:
kernel 6.1.0-9-amd64
Debian GNU/Linux 12 (bookworm)
mariadb  Ver 15.1 Distrib 10.11.3-MariaDB, for debian-linux-gnu (x86_64)
Server version: Apache/2.4.57 (Debian)
Server built:   2023-04-13T03:26:51
PHP 8.2.7
Nextcloud 27.0.0

**Closed** 2023-06-25 16:01 UTC
