### ISSUE TITLE
Export doesn't work in Firefox

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/passman#371] opened 2017-09-30 15:20 UTC
### Steps to reproduce
1. Apply the workaround from [here](https://github.com/nextcloud/passman/issues/264) in order to make sure you can download an export
2. Use firefox to open your passman vault
3. Make a csv export

### Expected behaviour
After the export has been generated, it can be downloaded

### Actual behaviour
The export generation finished, but the download doesn't start

### Note
The export does work in Chrome or Chromium

### Configuration
**Operating system**:
ubuntu 17.04

**Browser**:
Firefox 55.0.2 (64-bit)

**Extensions that might cause interference**:
None

**Passman version**:
2.4.1

**Operating system**:
? Hosting service

**Web server:**
Apache

**Database:**
MySql

**PHP version:** 
ea-php56
      
**cloud server:**
Nextcloud

**cloud version:**
12.0.3

**Comment by armaccloud** [comment] 2017-09-30 15:21
#264

**Comment by animalillo** [comment] 2017-09-30 16:14
not related with #264, this is an issue with the file generator or something maybe @brantje can give some insight here

**Comment by armaccloud** [comment] 2017-09-30 16:29
Ok, I've removed the reference.

**Comment by rugk** [comment] 2017-12-13 10:14
Actually I'd think this is a dupe of https://github.com/nextcloud/passman/issues/264. Same issue, basically. See also the workaround suggested there.

**Comment by kokoparkletal** [comment] 2018-03-08 19:06
I have the same issue.

On Firefox 58.0.2 64bits, Firefox ESR y Chrome (unknow version) (firefox ESR with password import and export and chrome with the flag of password import and export enabled.

Console chrome give me this error: 

`
angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:103 GET https://MY.SERVER/nextcloud/index.php/apps/passman/api/v2/file/undefined 500 (Internal Server Error)
(anonymous) @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:103
n @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:99
(anonymous) @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:96
(anonymous) @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:131
$eval @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:145
$digest @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:142
(anonymous) @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:145
e @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:45
(anonymous) @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:48
setTimeout (async)
k.defer @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:48
$evalAsync @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:145
(anonymous) @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:130
e @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:130
then @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:131
m @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:96
m.(anonymous function) @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:99
getFile @ fileservice.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:64
(anonymous) @ exporter-main.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:81
setTimeout (async)
C_Promise @ promise.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:49
getCredentialsWithFiles @ exporter-main.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:33
(anonymous) @ exporter-csv.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:36
setTimeout (async)
C_Promise @ promise.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:49
PassmanExporter.csv.export @ exporter-csv.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:35
(anonymous) @ export.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:83
(anonymous) @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:131
$eval @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:145
$digest @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:142
$apply @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:146
l @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:97
J @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:102
t.onload @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:103
XMLHttpRequest.send (async)
(anonymous) @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:103
n @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:99
(anonymous) @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:96
(anonymous) @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:131
$eval @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:145
$digest @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:142
$apply @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:146
(anonymous) @ angular.min.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:276
dispatch @ core.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:3
r.handle @ core.js?v=27e1a7e9c7730b55d1cbe2bd30a81cbc-3:3
`

**Comment by brantje** [comment] 2018-04-01 10:19
Dupe of #264. Closing

**Closed by brantje** 2018-04-01 10:19 UTC
Labels: bug
