### ISSUE TITLE
Blocking error on updating to 2.3.0 with the Nextcloud update of 15.0.8

### ISSUE THREAD

**Issue by MaxGitHubAccount** [nextcloud/passman#591] opened 2019-05-16 11:14 UTC
## Bug report
Updating Nextcloud to 15.0.8 fails when coming to passman update

### Steps to reproduce
1. Update NC 15.0.7 to 15.0.8 with passman 2.2.1
2. Update runs through nicely until it tells that there is an update for passman which cannot be canceled
3. Updating passman provides an error.

### Expected behaviour
Passman updates and Nextcloud can be used again

### Actual behaviour
There is an error:
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_passman_credentials ADD `compromised` LONGTEXT DEFAULT NULL': SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
Nextcloud is blocked - can only be resolved via deactivating passman via the console and removing it

### Configuration
**Operating system**:   debian stretch

**Browser**:      firefox

**Extensions that might cause interference**:   

**Passman version**:    2.2.1 to 2.3.0

**Web server:** apache

**Database:** mariadb

**PHP version:** PHP 7.0.33-0
      
**cloud server:** Nextcloud or ownCloud

**cloud version:** (see admin page or version.php) 15.0.8
  

#### Cloud log
<details>
{"reqId":"uNO29T3u7LQ1rKn3LJBi","level":3,"time":"2019-05-16T11:01:58+00:00","remoteAddr":"46.142.67.229","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=dQE%2FGkaHfzbWi8d5%2BPhFm14KbMjl0VMw1I0ve2ib0vQ%3D%3ALHcITDzkEH%2Fj3vc9u9Mp%2FgltK%2FuutStFoPt6QjjW5bU%3D","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0","version":"15.0.8.1","id":"5cdd45945e722"}
{"reqId":"uNO29T3u7LQ1rKn3LJBi","level":3,"time":"2019-05-16T11:01:58+00:00","remoteAddr":"46.142.67.229","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=dQE%2FGkaHfzbWi8d5%2BPhFm14KbMjl0VMw1I0ve2ib0vQ%3D%3ALHcITDzkEH%2Fj3vc9u9Mp%2FgltK%2FuutStFoPt6QjjW5bU%3D","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0","version":"15.0.8.1","id":"5cdd45945e722"}
{"reqId":"myDAXwf7Sz0x1xlECHkh","level":3,"time":"2019-05-16T11:05:54+00:00","remoteAddr":"46.142.67.229","user":"administrator","app":"settings","method":"POST","url":"/settings/apps/enable","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'ALTER TABLE oc_passman_credentials ADD `compromised` LONGTEXT DEFAULT NULL':\n\nSQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":128,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'ALTER TABLE oc_passman_credentials ADD `compromised` LONGTEXT DEFAULT NULL':\n\nSQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs",{"errorInfo":["42000",1118,"Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":964,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["42000",1118,"Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"ALTER TABLE oc_passman_credentials ADD `compromised` LONGTEXT DEFAULT NULL"]},{"file":"/var/www/nextcloud/lib/private/DB/Migrator.php","line":260,"function":"query","class":"Doctrine\\DBAL\\Connection","type":"->","args":["ALTER TABLE oc_passman_credentials ADD `compromised` LONGTEXT DEFAULT NULL"]},{"file":"/var/www/nextcloud/lib/private/DB/Migrator.php","line":83,"function":"applySchema","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/nextcloud/lib/private/DB/MDB2SchemaManager.php","line":123,"function":"migrate","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/nextcloud/lib/private/legacy/db.php","line":188,"function":"updateDbFromStructure","class":"OC\\DB\\MDB2SchemaManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Installer.php","line":134,"function":"updateDbFromStructure","class":"OC_DB","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/settings/Controller/AppSettingsController.php","line":441,"function":"installApp","class":"OC\\Installer","type":"->","args":["passman"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"enableApps","class":"OC\\Settings\\Controller\\AppSettingsController","type":"->","args":[["passman"],[]]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/nextcloud/lib/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php","Line":115,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs","Code":"42000","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":954,"function":"query","class":"Doctrine\\DBAL\\Driver\\PDOConnection","type":"->","args":["ALTER TABLE oc_passman_credentials ADD `compromised` LONGTEXT DEFAULT NULL"]},{"file":"/var/www/nextcloud/lib/private/DB/Migrator.php","line":260,"function":"query","class":"Doctrine\\DBAL\\Connection","type":"->","args":["ALTER TABLE oc_passman_credentials ADD `compromised` LONGTEXT DEFAULT NULL"]},{"file":"/var/www/nextcloud/lib/private/DB/Migrator.php","line":83,"function":"applySchema","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/nextcloud/lib/private/DB/MDB2SchemaManager.php","line":123,"function":"migrate","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/nextcloud/lib/private/legacy/db.php","line":188,"function":"updateDbFromStructure","class":"OC\\DB\\MDB2SchemaManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Installer.php","line":134,"function":"updateDbFromStructure","class":"OC_DB","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/settings/Controller/AppSettingsController.php","line":441,"function":"installApp","class":"OC\\Installer","type":"->","args":["passman"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"enableApps","class":"OC\\Settings\\Controller\\AppSettingsController","type":"->","args":[["passman"],[]]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/nextcloud/lib/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php","Line":106,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs","Code":"42000","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php","line":104,"function":"query","class":"PDO","type":"->","args":["ALTER TABLE oc_passman_credentials ADD `compromised` LONGTEXT DEFAULT NULL"]},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":954,"function":"query","class":"Doctrine\\DBAL\\Driver\\PDOConnection","type":"->","args":["ALTER TABLE oc_passman_credentials ADD `compromised` LONGTEXT DEFAULT NULL"]},{"file":"/var/www/nextcloud/lib/private/DB/Migrator.php","line":260,"function":"query","class":"Doctrine\\DBAL\\Connection","type":"->","args":["ALTER TABLE oc_passman_credentials ADD `compromised` LONGTEXT DEFAULT NULL"]},{"file":"/var/www/nextcloud/lib/private/DB/Migrator.php","line":83,"function":"applySchema","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/nextcloud/lib/private/DB/MDB2SchemaManager.php","line":123,"function":"migrate","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/nextcloud/lib/private/legacy/db.php","line":188,"function":"updateDbFromStructure","class":"OC\\DB\\MDB2SchemaManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Installer.php","line":134,"function":"updateDbFromStructure","class":"OC_DB","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/settings/Controller/AppSettingsController.php","line":441,"function":"installApp","class":"OC\\Installer","type":"->","args":["passman"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"enableApps","class":"OC\\Settings\\Controller\\AppSettingsController","type":"->","args":[["passman"],[]]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/nextcloud/lib/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php","Line":104}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0","version":"15.0.8.1","id":"5cdd45945d3b7"}
</details>
Apart from that there is now with 2.2.1 a certificate error again :-/
Results
=======
- passman
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.

**Comment by marcelstoer** [comment] 2019-05-16 13:23
Maybe one of the workarounds described here helps: https://craftcms.stackexchange.com/questions/11480/internal-server-error-sqlstate42000-1118-row-size-too-large

**Comment by joergmschulz** [comment] 2019-05-16 13:45
this might be related to some database errors I saw during the short time I had passman 2.3 up (now downgraded to 2.1 because of these errors):
`OCP\AppFramework\Db\DoesNotExistException: Did expect one result but found none when executing: query "SELECT * FROM `*PREFIX*passman_files` WHERE `id` = ? and `user_id` = ? "; parameters Array ( [0] => undefined [1] => xxxx ) ; limit ""; offset ""`

and 
`
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE `oc_passman_credentials` SET `guid` = ?,`vault_id` = ?,`user_id` = ?,`label` = ?,`description` = ?,`created` = ?,`changed` = ?,`tags` = ?,`email` = ?,`username` = ?,`password` = ?,`url` = ?,`icon` = ?,`expire_time` = ?,`files` = ?,`custom_fields` = ?,`otp` = ?,`hidden` = ?,`delete_time` = ?,`compromised` = ? WHERE `id` = ?' with params ["0xxxx", 1, "xxxx.yyyy", "Roundcube Webmail :: Posteingang", .....`

and: 
`... Row size too large ...`

**Comment by animalillo** [comment] 2019-05-16 13:54
A posible fix would be to change it from longtext to varchar or text, it is not supposed to grow that big since it will only store a boolean value (even if the field is encrypted it's not supposed to store that much data).

Checking other fields for it's size would also be a good idea we should avoid having too many longtext fields.

As a workaround, there are some options that can be tweaked on the mysql engine configuration: https://dba.stackexchange.com/questions/6598/innodb-create-table-error-row-size-too-large

**Comment by marcelstoer** [comment] 2019-05-16 13:59
> change it from longtext to varchar

How long would that varchar have to be?

**Comment by MaxGitHubAccount** [comment] 2019-05-16 14:10
As a workaround 2.2.1 works for me right now - I am waiting for the 2.3.1 then :-) I guess the 2.3.1 will contain the db update then and I won't have to change things manually to the db right now right?

**Comment by joergmschulz** [comment] 2019-05-20 19:06
Try the release of today: 2.3.1 seems to fix this. At least, for my installations it does. Caveat: you must clear your caches (ctrl-F5, CMD-R, ...).

**Comment by MaxGitHubAccount** [comment] 2019-05-20 22:25
Updating to 2.3.1 via the apps works - and also no passwords seemed to have disappeared! :-)

**Comment by MaxGitHubAccount** [comment] 2019-05-21 11:15
Still having the problem when trying to update to 2.3.1:
An error occured during the request. Unable to proceed.
An exception occurred while executing 'ALTER TABLE oc_passman_credentials ADD `compromised` LONGTEXT DEFAULT NULL': SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

**Comment by marcelstoer** [comment] 2019-05-21 11:18
> Still having the problem when trying to update to 2.3.1:

Well, the issue is still open 😉

**Comment by MaxGitHubAccount** [comment] 2019-05-21 11:20
> > Still having the problem when trying to update to 2.3.1:
> 
> Well, the issue is still open wink

Sorry I just had to re-write this because yesterday I thought it wold have worked after hitting the update button and everything worked - but the update button did not work and I didn't saw that :-D

**Comment by MaxGitHubAccount** [comment] 2019-06-08 20:19
For Nextcloud 16 all passwords are now shown to me with the newest passman app - I don't have this error anymore now

**Comment by animalillo** [comment] 2019-10-21 23:51
Since it seems to work with NC16 i think it's safe to close this issue then

**Closed by animalillo** 2019-10-21 23:51 UTC
Labels: Mediocre issue, bug
