### ISSUE TITLE
Cannot export credentials in FF57 or IE11

### ISSUE THREAD

**Issue by iamnotzerocool** [nextcloud/passman#373] opened 2017-10-03 01:33 UTC
### Steps to reproduce
1. Passman > Settings > Export credentials
2. Enter vault password
3. Says it's decrypting then nothing ever happens

### Expected behaviour
I would expect either a download to start or be prompted to download.

### Actual behaviour
Starting export
Decrypting credentials.....

### Configuration
**Operating system**:   
Windows 10

**Browser**:      
FireFox 57 Beta and Internet Explorer 11

**Extensions that might cause interference**:   
none

**Passman version**:    
Version: 2.1.4

**Operating system**:
Ubuntu 16.04.03

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.0
    
**cloud server:** Nextcloud or ownCloud
NextCloud

**cloud version:** (see admin page or version.php)
12.03
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
```
</details>

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by brantje** [comment] 2017-10-03 05:55
Duplicate of #264 or #371

**Closed by brantje** 2017-10-03 05:55 UTC
