### ISSUE TITLE
passman, The login window that resets when I click elsewhere

### ISSUE THREAD

**Issue by pwepwe973** [nextcloud/passman#746] opened 2022-07-22 01:18 UTC
Hello,

is it possible that the small window that allows you to identify yourself remains open when I go to look for my passwords in keepass because it resets and I have to re-enter everything again

Sincerely, SYLVAIN

**Comment by RossComputerGuy** [comment] 2022-11-22 23:07
I have the same problem except when I slightly move my mouse. I can't get past the vaults screen.

**Comment by binsky08** [comment] 2023-04-24 19:33
You talking about the browser extension?

**Comment by RossComputerGuy** [comment] 2023-04-25 19:18
Yes, I've had this issue with the browser extension.

**Comment by binsky08** [comment] 2023-04-26 06:42
duplicate of https://github.com/nextcloud/passman-webextension/issues/336 in the wrong repository

**Closed by binsky08** 2023-04-26 06:42 UTC
