### ISSUE TITLE
Support postgresql

### ISSUE THREAD

**Issue by jknockaert** [nextcloud/passman#274] opened 2017-03-10 11:22 UTC
What would be needed to be done in order to support postgresql?

**Comment by brantje** [comment] 2017-03-10 12:00
The queries need to be checked if they work, if they don't work they need to be fixed in such way they don't interfere with mysql / sql light.
Best is installing nextcloud local, clone passman repo and start fixing.

**Comment by jknockaert** [comment] 2017-03-10 12:09
OK. Will have a look at it. Are these queries grouped somewhere in the code or a bit everywhere?

**Comment by brantje** [comment] 2017-03-10 12:10
You can find the queries in the following folder: 
https://github.com/nextcloud/passman/tree/master/lib/Db
`<type>Mapper.php` are the file containing the queries.

**Comment by jknockaert** [comment] 2017-03-10 12:13
Has anyone ever tested passman on postgres? I mean, are we sure it doesn't work? Or is postgres unsupported simply because we don't know if it works or not?

**Comment by brantje** [comment] 2017-03-10 12:15
It's not supported because we don't know if it works. Might be a small chance that it works with out modifications. If that's the case then postgres should be added to tests.

**Comment by jknockaert** [comment] 2017-03-10 13:58
Having a quick look at it, it seems that the use of backticks (around field and table names) is a killer for postgres. Will consider how to work around this.

**Comment by brantje** [comment] 2017-03-10 14:05
One approach would be using something like this (pseudo code): 
```
$query = "SELECT `id,`user`,`pass` from table where `id`= %id
// Use the config service for the next part
if($config->db['db_type'] === 'postgres'){
  $query = "SELECT id,user,pass from table where id= %id
}
```

**Comment by jknockaert** [comment] 2017-03-10 14:06
Do we actually need the backticks? Mysql works without them (as long as there's no ambiguity).

**Comment by brantje** [comment] 2017-03-10 14:11
For consistency with other apps we need to use backticks.
Also it's good practice to use backticks with MariaDB / Mysql for the reason you given.
In the future we might add JOINS (for tags), so we will get duplicate `id` fields (cuz nextcloud requires an id field on every table).

**Comment by catumd** [comment] 2017-03-24 13:36
Можете дать пример кода тут на гитнабе где ести и PHP и postgresql запросы ? Буду благадарен я просто не знаю что искать.

**Comment by jknockaert** [comment] 2017-03-24 13:41
It remains to be seen if any modifications are required. I am now running the release version of Passman on an installation of nextcloud using a postgres database backend. The only modification I made is relaxing the requirement for mysql/sqlite. I still have to hit the first postgres-related bug.
As for the backticks: not sure at what stage they are handled, but obviously they're not fed into postgres, so I guess there's some abstraction layer involved.

**Comment by brantje** [comment] 2017-03-24 13:42
@catumd And now in english please ;)

**Comment by jberger** [comment] 2017-03-31 14:47
I would happily test (with non-important data of course). How can I install passman and bypass the requirement check for mysql or sqlite?

**Comment by jknockaert** [comment] 2017-03-31 14:50
@jberger add postgresql to the dependencies in appinfo/info.xml; next copy the modified app folder to you owncloud apps folder and enabled passman in the admin account.

**Comment by jberger** [comment] 2017-03-31 14:57
As I went to clone into the apps/ directory I noticed that the folder already existed to due my (failed) attempt to install from the app installer. Is it sufficient to just change it there?

**Comment by jknockaert** [comment] 2017-03-31 15:01
Ja should do. Not sure what happens upon upgrade, but in the worst case after an upgrade the app is disabled and you have to reapply the change.
Not sure what exactly is the right dependency string for postgres; either make a guess or peek in the dependency declaration of another app.

**Comment by jberger** [comment] 2017-03-31 15:02
pgsql worked, it was the string that is in config.php so after postgresql didn't work I tried that. Is there an IRC channel for passman? I don't really want to hijack this issue?

**Comment by amaymon** [comment] 2017-04-07 09:47
I'm already using passman over pgsql for some time now.
I have not seen any issue execpt some behavior like some edit or delete action not applied in database.
But it doesn't happen often, so I think the problem is between the screen and the chair.

What I've tested : 
Vault Creation 
Create new entry
Edit entry (and settings)
Exit and enter again in vault
Import Keepass2 CSV
Delete vault (by vault settings and admin request)

The only behavior I've now, but I 've to explore more, is when I delete a vault then create one with the same name / password, I've the previous tags (but no credential).

I'm not using passman as main vault nor daily so I may not find some problems or forget some. 

Whish this help on the subject

**Comment by animalillo** [comment] 2017-04-07 09:57
you should also test sharing.

Also please, review this document https://github.com/nextcloud/passman/wiki/Test-Protocol

**Comment by animalillo** [comment] 2017-04-07 09:57
and run unit tests

**Comment by amaymon** [comment] 2017-04-07 10:37
@animalillo  Ok fine. I'll do that when life will give me some time

**Comment by flocke** [comment] 2017-05-05 14:24
Any update on this?
I would love to deploy this addon on my Nextcloud server but don't have the time to test it a lot :(

**Comment by l1gi** [comment] 2017-05-05 18:41
I did not any reasonable testing but I am using passman on postgres for a month without any issue. I have just tweaked the config as mentioned above.

**Comment by rNoz** [comment] 2017-06-17 11:56
@l1gi which config? (amaymon 7apr?)

**Comment by l1gi** [comment] 2017-06-21 16:49
Sorry, it's info.xml.

<dependencies>
	<php min-version="5.6"/>
	<owncloud min-version="9" max-version="11" />
	<nextcloud min-version="9" max-version="12" />
	<database>sqlite</database>
	<database min-version="5.5">mysql</database>
	<database>pgsql</database>
	<lib>openssl</lib>
</dependencies>

Regards
-- 
l1gi

**Comment by jknockaert** [comment] 2017-07-19 08:00
@brantje What needs to happen to (officially) support postgres? Shall I make PR to add postgres to the dependencies in info.xml? I haven't seen a single postgres related bug reported.

**Comment by brantje** [comment] 2017-07-19 08:10
Officially, we need to update the info xml and add tests for postgres.
But since the DB tests are currently not working i think we can skip that.
Are you available to make tests for postgres when we need them?

**Comment by jknockaert** [comment] 2017-07-19 08:11
I'm not sure how you can make tests specifically for postgres. The framework seems pretty agnostic as far as the database backend is concerned.

**Comment by brantje** [comment] 2017-07-19 08:15
@animalillo and me need to look into the DB tests i guess. 
For now, adding postgress to info xml is fine with me.

**Comment by jknockaert** [comment] 2017-07-19 08:18
I had a quick look in the test files. There seem to be specifics to support mysql where tables are dumped. That should be doable in postgres? I didn't see any specifics for sqlite, which is supported already.

**Comment by jknockaert** [comment] 2017-07-19 08:22
PR is here: #337

**Comment by sanpii** [comment] 2017-07-30 18:14
I found a little bug during application update. The request to change `item_id` field type failed.

The correct request:

```sql
ALTER TABLE oc_passman_share_request ALTER item_id TYPE BIGINT USING item_id::bigint;
```

**Comment by brantje** [comment] 2017-07-30 18:14
DB upgrades are handles by nextcloud core. If that is a bug, please report it to the server repo.

**Comment by brantje** [comment] 2017-07-31 09:01
Support for postgresql is added in latest vesion, but not thoroughly tested. If there are issues feel free to open a new one.

**Closed by brantje** 2017-07-31 09:01 UTC
