### ISSUE TITLE
Several decryption errors after upgrade to 2.3.0

### ISSUE THREAD

**Issue by milkomeda** [nextcloud/passman#586] opened 2019-05-14 09:36 UTC
### Steps to reproduce
1. Upgrade to 2.3.0
2. Open vault in Nextcloud Passman App
3. See several errors on decryption

### Expected behaviour
List/show passwords without decryption errors.

### Actual behaviour
Several decryption errors on loading/opening vault. A lot of unencrypted/unusable passwords. Some passwords working.

### Configuration
**Operating system**:   Win 10 1809

**Browser**:      
Google Chrome
Google Chrome ist auf dem neuesten Stand.
Version 74.0.3729.131 (Offizieller Build) (64-Bit)

**Extensions that might cause interference**:   -

**Passman version**:    2.3.0

**Operating system**: Ubuntu 16.04

**Web server:** Nginx

**Database:** MySQL

**PHP version:** PHP 7.0.33-0ubuntu0.16.04.4
      
**cloud server:** Nextcloud

**cloud version:** 15.0.7

**Comment by milkomeda** [comment] 2019-05-14 09:36
Downgrading to 2.2.1 resolved all issues for the moment.

**Comment by MaxGitHubAccount** [comment] 2019-05-14 09:51
I am having the same issues - I also went back to 2.2.1 - However when there are missing / not to be encrypted passwords it would be nice to have this shown in a different way than just a dissapearing fly over - a better way would be having the not possible encrypting passwords in their own category, clickable or somehow to see what's harmed - if not I could assume everything is fine and some day I don't have the password I need.
apart from that I wonder if there were some kind of backup possibility of the passman files against a malicious update or some other fuckup - As I save all my credentials in my passman - even the one of my Nextcloud admin to e.g. install / deinstall passman it would be rather delicate xD

**Comment by newhinton** [comment] 2019-05-14 09:54
Do you have entries in the nextcloud log?

**Comment by MaxGitHubAccount** [comment] 2019-05-14 09:58
No errors I would assign to passman :-/

**Comment by newhinton** [comment] 2019-05-14 10:01
do you have big files?

i cannot reproduce those errors, so im trying to find a common denominator

**Comment by milkomeda** [comment] 2019-05-14 10:03
> do you have big files?
> 
> i cannot reproduce those errors, so im trying to find a common denominator

Yes 400+ passwords with a lot of incoming and outgoing shares

**Comment by animalillo** [comment] 2019-05-14 10:06
could you tell if this happens with all items, or only with shared ones?

We need to find a way to replicate this issue, any detail that could lead us to finding the cause will be very welcome!

**Comment by newhinton** [comment] 2019-05-14 10:06
if you reload the page, is it always the same passwords which are not working?

and how about the android app or the webextension, are they working properly?

**Comment by milkomeda** [comment] 2019-05-14 10:09
I couldn't tell if these errors occur on shared passwords or not. There were some working passwords perhaps 200 and some not. 

I didn't check if Android or webextension were working.

I'm investigating logs currently to provide some more information.

There is only a production system running currently. Can test something around after working hours.

**Comment by milkomeda** [comment] 2019-05-14 10:10
> if you reload the page, is it always the same passwords which are not working?

yes

**Comment by newhinton** [comment] 2019-05-14 10:12
it would be quiet helpful if you could find out what those passwords have in common, so tgat we can pinpoint why exactly those passwirds are affected

**Comment by milkomeda** [comment] 2019-05-14 11:25
Unfortunately no messages in nextcloud log.

I have tracked some JS errors in developer console.

```
Error: [ngRepeat:dupes] http://errors.angularjs.org/1.5.8/ngRepeat/dupes?p0=file%20in%20credential.files&p1=string%3AI&p2=I
    at VM413 passman.min.js:3
    at VM413 passman.min.js:7
    at VM413 passman.min.js:5
    at m.$digest (VM413 passman.min.js:5)
    at m.$apply (VM413 passman.min.js:5)
    at HTMLTableRowElement.<anonymous> (VM413 passman.min.js:7)
    at HTMLTableRowElement.dispatch (VM407 core.js:3)
    at HTMLTableRowElement.r.handle (VM407 core.js:3)
    
TypeError: Cannot read property 'length' of undefined
    at VM413 passman.min.js:27
    at VM413 passman.min.js:30
    at m.$digest (VM413 passman.min.js:5)
    at m.$apply (VM413 passman.min.js:5)
    at HTMLAnchorElement.<anonymous> (VM413 passman.min.js:7)
    at HTMLAnchorElement.dispatch (VM407 core.js:3)
    at HTMLAnchorElement.r.handle (VM407 core.js:3)
    
TypeError: Cannot read property 'length' of undefined
    at VM413 passman.min.js:30
    at VM413 passman.min.js:5
    at e (VM413 passman.min.js:3)
    at VM413 passman.min.js:3
```

I could not see any passwords shared with me using 2.3.0. Only 286 of 461 passwords were visible at all (none of the shared ones).

Some of the 286 passwords visible were not decrypted so not usable and triggering the above JS-errors on click.

**Comment by MaxGitHubAccount** [comment] 2019-05-14 12:03
Hm I get a 403 for a delete request:
https://XX/apps/passman/admin/delete-requests
and console errors which don't seem to be related:
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("script-src"). passman.min.js:31:12977

Apart of that I don't see any non-working Passwords - I only see that there are now only 207 availible while there were 210 with the previous version
![passman-errors](https://user-images.githubusercontent.com/476371/57696105-48a8e400-7650-11e9-8563-5f1a2fb4bd5c.png)

I tried to do an export into json or csv (in order to make a diff) but or it's taking a while or it's not working :-/

**Comment by MaxGitHubAccount** [comment] 2019-05-14 12:11
I will go through it manually to check and post more insights about things those passwords might have in common

**Comment by Luticus** [comment] 2019-05-14 14:40
I'm also having this same problem.  I downgraded to the older version which did fix my problem.  I suspect that some of the affected passwords may be shared, but can't confirm that it's only shared ones because there's 10+ that are broken for me.  I'll do some research tonight and post any errors or results I get on it.  Hopefully that will help.

**Comment by MaxGitHubAccount** [comment] 2019-05-14 18:47
It appears that those passwords which disappear where shared with me through another account.

**Comment by e-alfred** [comment] 2019-05-15 12:59
Okay, this is the error I get on the browser console:

```
Error: [ngRepeat:dupes] http://errors.angularjs.org/1.5.8/ngRepeat/dupes?p0=field%20in%20storedCredential.custom_fields&p1=string%3AI&p2=I
N/<@https://server/apps/passman/js/passman.min.js?v=17c270bd-4:3:596
compile/</<@https://server/apps/passman/js/passman.min.js?v=17c270bd-4:7:23459
$watchCollection/<@https://server/apps/passman/js/passman.min.js?v=17c270bd-4:5:5455
$digest@https://server/apps/passman/js/passman.min.js?v=17c270bd-4:5:6102
$apply@https://server/apps/passman/js/passman.min.js?v=17c270bd-4:5:7549
compile/</<@https://server/apps/passman/js/passman.min.js?v=17c270bd-4:7:10002
dispatch@https://server/core/vendor/core.js?v=17c270bd-4:3:6414
add/r.handle@https://server/core/vendor/core.js?v=17c270bd-4:3:3224
passman.min.js:4:25218
    e https://server/apps/passman/js/passman.min.js?v=17c270bd-4:4
    get https://server/apps/passman/js/passman.min.js?v=17c270bd-4:4
    $digest https://server/apps/passman/js/passman.min.js?v=17c270bd-4:5
    $apply https://server/apps/passman/js/passman.min.js?v=17c270bd-4:5
    compile https://server/apps/passman/js/passman.min.js?v=17c270bd-4:7
    dispatch https://server/core/vendor/core.js?v=17c270bd-4:3
    handle https://server/core/vendor/core.js?v=17c270bd-4:3
```

The password is shared with a public link by me.

**Comment by newhinton** [comment] 2019-05-15 13:23
We know why this is occuring, and will be fixed soon

**Comment by marcelstoer** [comment] 2019-05-15 20:21
@milkomeda 
> Some of the 286 passwords visible were not decrypted 

The ones which failed to decrypt were the ones you shared with _others_?

**Comment by marcelstoer** [comment] 2019-05-17 13:52
Shouldn't this be assigned to the 2.3.1. milestone?

**Comment by IBBoard** [comment] 2019-05-17 19:03
Is there a temporary fix for this? (other than patching the files by hand and having NextCloud complain about modified files) Can we update the database by hand, or not because the fields have to be specially encrypted?

**Comment by e-alfred** [comment] 2019-05-17 21:04
As a temporary measure removing any sharing from failing passwords might solve the problem (at least that worked for me).

**Closed** 2019-05-19 15:24 UTC
Labels: review

**Comment by marcelstoer** [comment] 2019-05-19 20:38
I can confirm that #590 fixes the decryption issues described here. I'm now running the latest Git master and Passman shows me both credentials shared by and with me.

**Comment by milkomeda** [comment] 2019-05-21 11:21
2.3.1 is working for me. Thank you 👍

**Comment by trummerschlunk** [comment] 2019-08-05 11:22
Hi, keepass import still does not work here. keepassXC import stops after 'read' progress (1 entry before end). Then I exported my database with standard keepass (win10) and import passes 'read' process, starts adding, but stops 2 entries before finishing - effectively not importing a single entry.
Any ideas? Thanks
