### ISSUE TITLE
Error during decryption

### ISSUE THREAD

**Issue by ShinyShrimp** [nextcloud/passman#437] opened 2018-01-26 09:19 UTC
## Bug report
I get several "error during decryption" messages as soon as I open my vault. The passwords that can't be decrypted are not always the same ones.

### Steps to reproduce
1. Go to Passman App in Nextcloud
2. Click on my vault and enter password
3. Not all passwords can be decrypted

### Expected behaviour
All my passwords get decrypted.

### Actual behaviour
Some of my passwords are still encrypted. 

Error message:
[error during decryption.pdf](https://github.com/nextcloud/passman/files/1667230/error.during.decryption.pdf)

### Configuration
**Operating system**:  Windows 10 

**Browser**:    Chrome Version 63.0.3239.132 (Same problem in different browsers and chrome extension)

**Extensions that might cause interference**:   

**Passman version**:    2.1.4

**Operating system**: Ubuntu 4.4. (shared hosting with ssh access)

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.1 (CGI)
      
**cloud server:** Nextcloud 

**cloud version:** 12.0.5

#### Cloud log

<details>
<summary>Cloud log errors</summary>

1. Method OC_L10N_String::__toString() must return a string value at /www/htdocs/.../.../nextcloud/lib/private/L10N/L10N.php#85

2. vsprintf(): Too few arguments at /www/htdocs/.../.../nextcloud/lib/private/legacy/l10n/string.php#72

</details>

**Comment by animalillo** [comment] 2018-01-26 09:28
Is there any errors on the browser console? (Allow it from the nextcloud config and then press f12 while on the passman app)

**Comment by ShinyShrimp** [comment] 2018-01-26 09:52
How do I allow it in the nextcloud config?

In my browser console I see only these two warnings: 

`core.js?v=c3d3e57eeea6b7b572aa850e6b88a333-16:sourcemap:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

`Crypto stuff initialized
initEngines @ passman.min.js?v=c3d3e57eeea6b7b572aa850e6b88a333-16:27`

and this message:
`Slow network is detected. Fallback font will be used while loading: https://.../apps/passman/css/fontawesome-webfont.woff2?v=4.6.3`

**Comment by ShinyShrimp** [comment] 2018-02-13 23:51
Sadly no progress here... I migrated to Lastpass until Passman gets more robust. also the migration to Lastpass was complicated because of the broken exporter. 

Any information out there when the next version will be released?

**Comment by peychart** [comment] 2022-04-15 00:54
Same error with 2.3.7 in 2022 : so what?... ;-)
(How can I convince my boss to adopt nextcloud if essential features are not possible?)

**Comment by binsky08** [comment] 2022-04-15 01:51
> Same error with 2.3.7 in 2022 : so what?... ;-) (How can I convince my boss to adopt nextcloud if essential features are not possible?)

@peychart could you please try it with the current version 2.4.0
If the error persists, please provide more information about what you did, browser, nextcloud version, php version, ... and a log file if possible.

**Comment by peychart** [comment] 2022-04-15 05:06
Nextcloud 22.2.6 : Sorry, I cannot try with 2.4 because passman do not ask for this new vesion,
Nexcloud 23.0.3 : cannot install on NC23 because not compatible (unknown fomat with database.xml) :-(

Debian 10.12 with PHP 7.3.31 in the last version (16.1-1) of turnkey-nextcloud template for Proxmox ...
Browser : Brave 1.37.113 or Firefox 99.0

**Comment by peychart** [comment] 2022-04-15 05:14
LOG:
{"reqId":"psgTd2Fd6hkFMBhq5BPA","level":3,"time":"2022-04-15T05:13:38+00:00","remoteAddr":"43.249.178.31","user":"phil","app":"passman","method":"POST","url":"/index.php/apps/passman/api/v2/sharing/save","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36","version":"22.2.6.2"}
{"reqId":"noc3LDJDAtNNgERqIEnS","level":3,"time":"2022-04-15T05:13:38+00:00","remoteAddr":"43.249.178.31","user":"phil","app":"passman","method":"GET","url":"/index.php/apps/passman/api/v2/vaults/9F632FE1-FFBE-4D9D-BE5A-4585B0124AEC","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36","version":"22.2.6.2"}
{"reqId":"MZ9INTkmAKb8jfA3bbdW","level":3,"time":"2022-04-15T05:13:38+00:00","remoteAddr":"43.249.178.31","user":"phil","app":"passman","method":"GET","url":"/index.php/apps/passman/api/v2/sharing/vault/9F632FE1-FFBE-4D9D-BE5A-4585B0124AEC/get","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36","version":"22.2.6.2"}
{"reqId":"m5PSBG57hnzw0j84gjQ4","level":3,"time":"2022-04-15T05:13:43+00:00","remoteAddr":"43.249.178.31","user":"admin","app":"passman","method":"GET","url":"/index.php/apps/passman/api/v2/sharing/pending","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0","version":"22.2.6.2"}
{"reqId":"WF3QMyj9qTZqZ2s6iccA","level":3,"time":"2022-04-15T05:13:47+00:00","remoteAddr":"43.249.178.31","user":"admin","app":"passman","method":"GET","url":"/index.php/apps/passman/api/v2/vaults/643C6849-6A5F-401E-9708-7F192929EA82","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0","version":"22.2.6.2"}
{"reqId":"oPaEx6UXjINM0QmhaOAm","level":3,"time":"2022-04-15T05:13:47+00:00","remoteAddr":"43.249.178.31","user":"admin","app":"passman","method":"GET","url":"/index.php/apps/passman/%7B%7BcustomIcon.data%7D%7D","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0","version":"22.2.6.2"}
{"reqId":"JvUuT6QI0sksdGFwWu0M","level":3,"time":"2022-04-15T05:13:47+00:00","remoteAddr":"43.249.178.31","user":"admin","app":"passman","method":"GET","url":"/index.php/apps/passman/api/v2/icon/list","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0","version":"22.2.6.2"}
{"reqId":"V4JTwR0VBrBBr7AjwMpN","level":3,"time":"2022-04-15T05:13:47+00:00","remoteAddr":"43.249.178.31","user":"admin","app":"passman","method":"GET","url":"/index.php/apps/dashboard/","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0","version":"22.2.6.2"}
{"reqId":"HKEnaUakdRVo17CZZ5ay","level":3,"time":"2022-04-15T05:13:51+00:00","remoteAddr":"43.249.178.31","user":"admin","app":"passman","method":"PATCH","url":"/index.php/apps/passman/api/v2/credentials/ED00896F-3E65-4013-B4A8-BA6928A1396A","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0","version":"22.2.6.2"}
{"reqId":"WdKwgHro7Xx5vXCbWZJi","level":3,"time":"2022-04-15T05:13:51+00:00","remoteAddr":"43.249.178.31","user":"admin","app":"passman","method":"GET","url":"/index.php/apps/passman/api/v2/sharing/pending","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0","version":"22.2.6.2"}
{"reqId":"yE8LHCfmwTQAlM5dgUTG","level":3,"time":"2022-04-15T05:13:54+00:00","remoteAddr":"43.249.178.31","user":"phil","app":"passman","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36","version":"22.2.6.2"}

**Comment by peychart** [comment] 2022-04-15 05:22
Process:
- a new wallet is created in user,
- a new wallet is created in admin,
- a new passwd is created in admin wallet,
- this new passwd is shared for user,
- admin passwd is destroyed (all fieds seem something like that : "eyJpdiI6IlY3NVAxZ1lpa3E1ak5LdkdEWjU1b3ciLCJ2IjoxLCJpdGVyIjoxMDAwLCJrcyI6MjU2LCJ0cyI6NjQsIm1vZGUiOiJjY20iLCJhZGF0YSI6IiIsImNpcGhlciI6ImFlcyIsInNhbHQiOiJnRUp4YkJ2T3M0byIsImN0IjoiVzVGZjhraFh2cWcrVkEifQ")...

**Comment by binsky08** [comment] 2022-04-15 09:02
First of all, php7.3 has reached its end of life.

So please update at least to php7.4 to geht further updates for Passman.

[https://www.php.net/supported-versions.php](https://www.php.net/supported-versions.php)

But if your vault is already corrupted, the update should not fix that. (not sure at this point)

Unfortunately it seems to be a known problem #553

I'll try to take a look to see if the bug persists in the current version.

**Comment by peychart** [comment] 2022-04-15 09:07
no, only the shared (test) password is corrupted ... ;-)
Thanks for your advice.

**Comment by binsky08** [comment] 2022-04-15 10:49
> LOG: {"reqId":"psgTd2Fd6hkFMBhq5BPA","level":3,"time":"2022-04-15T05:13:38+00:00","remoteAddr":"43.249.178.31","user":"phil","app":"passman","method":"POST","url":"/index.php/apps/passman/api/v2/sharing/save","message":"/appinfo/app.php is not loaded when \OCP\AppFramework\Bootstrap\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36","version":"22.2.6.2"} ...

The bug "/appinfo/app.php is not loaded when \OCP\AppFramework\Bootstrap\IBootstrap on the application class is used." described by your logs is already fixed.

> Nexcloud 23.0.3 : cannot install on NC23 because not compatible (unknown fomat with database.xml) :-(

The no longer supported database.xml was removed with version 2.3.10

Only Passman 2.4.0 is supported for Nexcloud 23!

> Process:
> 
>     * a new wallet is created in "user" account,
> 
>     * a new wallet is created in "admin" account,,
> 
>     * a new passwd is created in the "admin" wallet,
> 
>     * this new passwd is shared for "user",
> 
>     * passwd of "admin" wallet is destroyed (all fieds are broken : "eyJpdiI6IlY3NVAxZ1lpa3E1ak5LdkdEWjU1b3ciLCJ2IjoxLCJpdGVyIjoxMDAwLCJrcyI6MjU2LCJ0cyI6NjQsIm1vZGUiOiJjY20iLCJhZGF0YSI6IiIsImNpcGhlciI6ImFlcyIsInNhbHQiOiJnRUp4YkJ2T3M0byIsImN0IjoiVzVGZjhraFh2cWcrVkEifQ")...

I was not able to reproduce the described sharing problem, see comment: https://github.com/nextcloud/passman/issues/606#issuecomment-1100028551

**Comment by binsky08** [comment] 2022-04-15 10:55
Since Passman 2.1.4 is about 5 years old and the bug seems to have been fixed between version 2.1.4 and 2.4.0, I am closing the original issue.
Please reopen the issue if the bug reproducibly occurs with a fresh >= 2.4.0 installation.

**Closed by binsky08** 2022-04-15 10:55 UTC
