### ISSUE TITLE
error 500 in ajax query while saving a credential

### ISSUE THREAD

**Issue by skylupo** [nextcloud/passman#620] opened 2019-09-27 16:50 UTC
### Bug report

I cannot save any credential anymore  ...
- Using nextcloud2 15.0.2
- Using passman 2.3.2

I want to edit some credential, and they're all marked as "compromise", very strange, and certainly incorrect ...
I update some credential, then click on "save", then the "working gif icon" will run without stopping.

If I open my debugger, I can see an ajax query fired (with the PATCH method) when clicking on the save button, and the query answer is "error 500".

the ajax url is : https://xxxxxxxxxx.net/index.php/apps/passman/api/v2/credentials/5704xxxxxxxxxxxxxxFF

### Steps to reproduce
1. use nextcloud2 15.0.2 and passman 2.3.2
2. enter passman, choose any vault, and unlock it
3. choose any credential to edit, and it will be marked as "compromised"
4. modify the credential password, then click on the "save button"
5. the icon on the button will change in a gear that never stop to turn, and the credential is not updated

### Expected behaviour
The credantial should be updated

### Actual behaviour
Impossible to update any credential

### Configuration

**Browser**:      
Firefox 69

**Extensions that might cause interference**:   
none 

**Passman version**:
2.3.2

**Operating system**: 
Linux  Ubuntu 19.04

**Web server:**
Debian 9.9

**Database:**
MariaDb 10.1.38

**PHP version:**
PHP 7.0

**cloud server:** Nextcloud or ownCloud
nextcloud

**cloud version:** (see admin page or version.php)
nextcloud 15.0.2  
   
#### Browser log
<details>
<summary>Browser log</summary>
a) The Ajax answer is:

This application requires JavaScript for correct operation. Please enable JavaScript and reload the page.
Cloud2
Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details

    Remote Address: xx.xx.xx.xx
    Request ID: vPtvzg78L8VLQb7dtXjj

</details>   

#### Cloud log
<details>
<summary>Cloud log</summary>

```
"line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/xxxxxxx.net\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","Line":107,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline.","Code":"42000"
```
</details>

Seems to be some issue with the database server ...
Can you help me ?
Thanks
Sky

**Comment by bennidi** [comment] 2019-10-02 09:51
I am seeing a similar behaviour on my new nextcloud (latest release from two weeks ago). I can not store the password and it is marked as compromise. The save button keeps spinning.
Does passman require mcrypt? I have php 7.2 which has no official mcrypt module anymore.

**Comment by animalillo** [comment] 2019-10-21 23:37
Passman does not require mcrypt module, i run it on php 7.2 altought it uses cryptographic functions server side for the server side encryption part that you should support on your php install.

The issue is most likely something related with a data field being too long to be stored on mysql, it would help to know the length of all the fields you are sending to the server for storage.

**Comment by animalillo** [comment] 2019-10-21 23:52
Maybe this is of some help
https://mariadb.com/kb/en/library/troubleshooting-row-size-too-large-errors-with-innodb/

**Comment by binsky08** [comment] 2021-09-27 09:50
Could not reproduce that with the current Passman version.
If it is still an issue, please reopen.

**Closed by binsky08** 2021-09-27 09:50 UTC
