### ISSUE TITLE
passman not working with Owncloud 10.1

### ISSUE THREAD

**Issue by inguy24** [nextcloud/passman#559] opened 2019-02-22 17:12 UTC
## Bug report
Owncloud Instance 10.1.0.4

In app.php line 1178:

  App "Passman" cannot be installed because the following dependencies are not fulfilled: ownCloud
  10.0 or lower is required.

### Steps to reproduce
1. Upgrade Owncloud
2. App must be disabled either through web page or OCC command
3. App no longer in the market and cannot be re-enabled through OCC command

### Expected behaviour
App should have been transitioned to new version.

### Actual behaviour
App is not compatible with new version. 

### Configuration
Ubuntu with Owncloud on virtual machine

**Browser**:      
Chrome

**Extensions that might cause interference**:   
Unknown

**Passman version**:    
Latest

**Operating system**:
Ubuntu 16.04 LTS 

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
 7
    
**cloud server:** Nextcloud or ownCloud
ownCloud

**cloud version:** (see admin page or version.php)
  10.1.04
   

## Feature request

**User type**: Logged-in 

**User level**: Beginners

Upgrade for compatibility with ownCloud 10.1

**Comment by kurtis318** [comment] 2019-02-24 01:22
I also ran into this issue today.  It would be nice if there was a standalone app (GUI or command-line) to access the pacman database.   As of now, there is no way to access 200+ passwords I have stored.

**Comment by larwood** [comment] 2019-02-26 10:45
I blame myself I forgot to check extension compatibility before upgrading to 10.1.0.

I decided I can't live without my password manager so I did a downgrade back to 10.0.10 and restore.

**Comment by kurtis318** [comment] 2019-02-27 04:00
> I blame myself I forgot to check extension compatibility before upgrading to 10.1.0.
> 
> I decided I can't live without my password manager so I did a downgrade back to 10.0.10 and restore.

How did you do the downgrade and restore?  Thanks...

**Comment by larwood** [comment] 2019-02-27 05:33
> > I blame myself I forgot to check extension compatibility before upgrading to 10.1.0.
> > I decided I can't live without my password manager so I did a downgrade back to 10.0.10 and restore.
> 
> How did you do the downgrade and restore? Thanks...

I followed the guide: https://doc.owncloud.org/server/admin_manual/maintenance/restore.html

I do a tarball install so it was a matter of restoring my directories from backup and then the database.

**Comment by yorktown82** [comment] 2019-03-05 13:28
I forced the upgrade too, and like a good IT person, I didn't backup anything.... So I was unable to perform the restore documented above... Since I have nothing to lose, I.....

1) Deleted or move the signature.json out of /var/www/owncloud/apps/passman/appinfo

2) Modify /var/www/owncloud/apps/passman/appinfo/info.xml  .... Change line 43 Max=10.0 to max=10.1

4) restarted apache

3) enable the app in settings - apps - disabled apps.

since the package is signed, deleting the signature file to avoid the code integrity check error for this package. Probably not the best workaround, but passman at least works for me so I can export for my eventual migration to nextcloud... :)

**Comment by kurtis318** [comment] 2019-03-05 17:04
> I forced the upgrade too, and like a good IT person, I didn't backup anything.... So I was unable to perform the restore documented above... Since I have nothing to lose, I.....
> 
> 1. Deleted or move the signature.json out of /var/www/owncloud/apps/passman/appinfo
> 2. Modify /var/www/owncloud/apps/passman/appinfo/info.xml  .... Change line 43 Max=10.0 to max=10.1
> 3. restarted apache
> 4. enable the app in settings - apps - disabled apps.
> 
> since the package is signed, deleting the signature file to avoid the code integrity check error for this package. Probably not the best workaround, but passman at least works for me so I can export for my eventual migration to nextcloud... :)

Thanks for the process.   It worked for me.  There is a code integrity check when the signature.json file is removed.  This goes away  when the passman app is disabled.

**Comment by inguy24** [comment] 2019-03-05 19:14
> I forced the upgrade too, and like a good IT person, I didn't backup anything.... So I was unable to perform the restore documented above... Since I have nothing to lose, I.....
> 
> 1. Deleted or move the signature.json out of /var/www/owncloud/apps/passman/appinfo
> 2. Modify /var/www/owncloud/apps/passman/appinfo/info.xml  .... Change line 43 Max=10.0 to max=10.1
> 3. restarted apache
> 4. enable the app in settings - apps - disabled apps.
> 
> since the package is signed, deleting the signature file to avoid the code integrity check error for this package. Probably not the best workaround, but passman at least works for me so I can export for my eventual migration to nextcloud... :)

Thanks... this was a great workaround. At least everything is restored and working for now!

**Comment by haryseldon2** [comment] 2019-03-06 23:13
Does anybody know if passman will be supported in Owncloud 10.1 or greater?
Is the support for Owncloud discontinued?

**Comment by teagulp** [comment] 2019-03-09 08:37
I am an experienced developer (mainly C++ but also Java and python). If someone could give me some pointers what is the cause of this problem. What need to be done and where to read up I could give this a go.

**Comment by RMoser93** [comment] 2019-03-16 12:40
> 
> 
> I forced the upgrade too, and like a good IT person, I didn't backup anything.... So I was unable to perform the restore documented above... Since I have nothing to lose, I.....
> 
>     1. Deleted or move the signature.json out of /var/www/owncloud/apps/passman/appinfo
> 
>     2. Modify /var/www/owncloud/apps/passman/appinfo/info.xml  .... Change line 43 Max=10.0 to max=10.1
> 
>     3. restarted apache
> 
>     4. enable the app in settings - apps - disabled apps.
> 
> 
> since the package is signed, deleting the signature file to avoid the code integrity check error for this package. Probably not the best workaround, but passman at least works for me so I can export for my eventual migration to nextcloud... :)

Thank you, passman work now on OC 10.1.0 stable

**Comment by animalillo** [comment] 2019-05-20 19:57
Since it seems to be working for people i will close this issue now.

**Closed by animalillo** 2019-05-20 19:57 UTC

**Comment by TomaszWaszczyk** [comment] 2019-07-02 23:13
Seems that on 10.1.1 Does not work ;/

**Comment by haryseldon2** [comment] 2019-07-03 13:25
> 
> 
> Seems that on 10.1.1 Does not work ;/

Actually it is working fine in my OC 10.2.0. Also it worked under 10.1.1. I followed de instructions to remove the signature file and edit the min version in the config file without issues.
