### ISSUE TITLE
OC_L10N_String::toString() must return string value

### ISSUE THREAD

**Issue by Luticus** [nextcloud/passman#306] opened 2017-06-03 01:35 UTC
## Bug report
Found the following entries in my logs and thought i should report it in case it's important:

{"reqId":"WTH1MX8AAQEAAH29ISwAAAAK","level":3,"time":"2017-06-02T19:30:57-04:00","remoteAddr":"192.168.1.133","user":"Bob","app":"PHP","method":"GET","url":"\/index.php\/apps\/passman\/api\/v2\/language?lang=en","message":"vsprintf(): Too few arguments at \/var\/www\/owncloud\/lib\/private\/legacy\/l10n\/string.php#72","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:47.0) Gecko\/20100101 Firefox\/47.0","version":"12.0.0.29"}
{"reqId":"WTH1MX8AAQEAAH29ISwAAAAK","level":3,"time":"2017-06-02T19:30:57-04:00","remoteAddr":"192.168.1.133","user":"Bob","app":"PHP","method":"GET","url":"\/index.php\/apps\/passman\/api\/v2\/language?lang=en","message":"Method OC_L10N_String::__toString() must return a string value at \/var\/www\/owncloud\/lib\/private\/L10N\/L10N.php#85","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:47.0) Gecko\/20100101 Firefox\/47.0","version":"12.0.0.29"}

### Configuration
**Operating system**:   Debian 8 Jessie

**Browser**:      Firefox 47

**Extensions that might cause interference**:   

**Passman version**:    2.1.2

**Operating system**:  Debian 8

**Web server:**  Apache2

**Database:**  mysql 5

**PHP version:**php 5.5
      
**cloud server:** Nextcloud 12

**cloud version:** (see admin page or version.php) 12

#### Cloud log

<details>
<summary>Cloud log</summary>

```
{"reqId":"WTH1MX8AAQEAAH29ISwAAAAK","level":3,"time":"2017-06-02T19:30:57-04:00","remoteAddr":"192.168.1.133","user":"Bob","app":"PHP","method":"GET","url":"\/index.php\/apps\/passman\/api\/v2\/language?lang=en","message":"vsprintf(): Too few arguments at \/var\/www\/owncloud\/lib\/private\/legacy\/l10n\/string.php#72","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:47.0) Gecko\/20100101 Firefox\/47.0","version":"12.0.0.29"}
{"reqId":"WTH1MX8AAQEAAH29ISwAAAAK","level":3,"time":"2017-06-02T19:30:57-04:00","remoteAddr":"192.168.1.133","user":"Bob","app":"PHP","method":"GET","url":"\/index.php\/apps\/passman\/api\/v2\/language?lang=en","message":"Method OC_L10N_String::__toString() must return a string value at \/var\/www\/owncloud\/lib\/private\/L10N\/L10N.php#85","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:47.0) Gecko\/20100101 Firefox\/47.0","version":"12.0.0.29"}

```
</details>

**Comment by brantje** [comment] 2017-06-03 09:22
Duplicate of #209

**Comment by moretocome** [comment] 2017-08-30 20:22
Same errors in #342 might be related. I see these errors in my log, after my crypt fails to decrypt.

**Comment by brantje** [comment] 2017-10-29 18:41
sprintf issue is solved in master, feel free to open this issue if the problem persists.

**Closed by brantje** 2017-10-29 18:41 UTC
