### ISSUE TITLE
export doesn't recognize custom fields anymore

### ISSUE THREAD

**Issue by jkischel** [nextcloud/passman#305] opened 2017-05-25 13:07 UTC
### Steps to reproduce
1. create a test password entry
2. add a custom field, i.e. "serial key" and give it a value, i.e. "12345"
3. start an export of the container

### Expected behaviour
All data is being exported (did already work in Passman 1.3.38).

### Actual behaviour
not even one of the custom fields is being exported.

### Configuration
**Passman version**:    2.1.2
**cloud server:** ownCloud
**cloud version:** 9.1.4 (stable)

**Comment by jkischel** [comment] 2017-05-25 13:08
ah, and I just wanted to mention that this makes a backup quite useless as I'm using passman to store lots of additional information.

**Comment by animalillo** [comment] 2017-05-25 13:38
we will check this out this weekend, as of a workaround, you can make a backup of the database

**Comment by animalillo** [comment] 2017-06-02 11:29
I have some work done here, but the files are giving me some trouble, i will keep you updated

**Comment by jkischel** [comment] 2017-06-02 17:20
maybe I have an idea:
As CSV isn't that flexible as XML or JSON is, maybe you could export the custom fields the way that you export field1.name, field1.type, field1.value, field2.name, field2.type, field2.value, ...

**Comment by animalillo** [comment] 2017-06-02 19:55
oh, you see, the problem is gathering the files, as it's an asynchronous process and breaks the current logic of the script and i have to work on a way around that.
Of course, the custom fields will be a json field even if it's exported as a CSV

**Comment by animalillo** [comment] 2017-06-04 17:13
I have just added custom fields and files into the export, took a little bit more than I initially expected, but there it is.
I will wait for @brantje to review the code but i tested it and it works on my setup, we will close this issue once the code gets merged.

**Closed** 2017-07-01 16:37 UTC
